### ISSUE TITLE
Add Finos logo

### ISSUE THREAD

**Issue by godds** [ScottLogic/logo-bricks#22]
https://www.mecabricks.com/en/models/Gejeb8RDvKX

**Comment by ColinEberhardt** [comment]
This needs re-colouring due to availability issues with the bricks. I've re-coloured and ensured I can order ~20 sets:

https://www.bricklink.com/v2/wanted/search.page?wantedMoreID=2155376

This uses `Blue` for the background and `Medium Blue` for the background logo colour.

**Comment by ColinEberhardt** [comment]
Colour conversion table - just for future reference https://www.eurobricks.com/forum/index.php?/forums/topic/91641-bricklinklego-color-translation-table/

**Comment by ColinEberhardt** [comment]
Re-coloured model here: https://www.mecabricks.com/en/models/eDvVr9b0vBR
